c221/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    path('logout/', auth_views.LogoutView.as_view(),name='logout'),
    path('signup/', views.SignUp.as_view(),name='signup'),
]

c221/c221/urls.py
from django.contrib import admin
from django.urls import path, include
from c221 import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name="home"),
    path('test/', views.TestPage.as_view(), name="test"),
    path('thanks/', views.ThanksPage.as_view(), name="thanks"),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('accounts/', include("django.contrib.auth.urls")),
    path('posts/', include("posts.urls", namespace="posts")),
]

c221/posts/urls.py
from django.urls import path
from posts import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(), name="all"),
    path("new/", views.CreatePost.as_view(), name="create"),
    path("by/<username>/", views.UserPosts.as_view(), name="for_user"),
    path("by/<username>/<int:pk>/", views.PostDetail.as_view(), name='single'),
    path("delete/<int:pk>/", views.DeletePost.as_view(), name='delete'),
]

c221/accounts/models.py
from django.db import models
from django.contrib import auth
from django.utils import timezone

# Create your models here.

class User(auth.models.User, auth.models.PermissionsMixin):
    
    def __str__(self):
        return '@{}'.format(self.username)

c221/posts/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.utils import timezone
import misaka

User = get_user_model()

# Create your models here.

class Post(models.Model):
    user = models.ForeignKey(User, related_name="posts", on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=100, default='Title')
    created_at = models.DateTimeField(auto_now=True)
    message = models.TextField()
    message_html = models.TextField(editable = False)

    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        self.message_html = misaka.html(self.message)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("posts:single", kwargs={"username": self.user.username, "pk":self.pk})

    class Meta:
        ordering = ["-created_at"]
        unique_together = ["user", "title"]

class Comment(models.Model):
    blogpost = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    text = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    created_date = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ["-created_date"]
        unique_together = ["author",]
    
    def get_absolute_url(self):
        return reverse('posts:all')

    def __str__(self):
        return self.text

    @property
    def num_of_comments(self):
        return Comment.objects.filter(blogpost=self).count()

c221/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class UserCreateForm(UserCreationForm):
    class Meta:
        fields = ('username', 'email', 'password1', 'password2')
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Display name'
        self.fields['email'].label = 'Email address'

c221/posts/forms.py
from django import forms
from posts import models

class PostForm(forms.ModelForm):
    class Meta:
        fields = ('message',)
        model = models.Post


class CommentForm(forms.ModelForm):
    class Meta:
        fields = ['text']
        model = models.Comment
        

c221/accounts/views.py
from django.shortcuts import render
from django.contrib.auth import login, logout
from django.urls import reverse_lazy
from django.views.generic import CreateView
from accounts import forms

# Create your views here.

class SignUp(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

c221/c221/views.py
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.views.generic import TemplateView

class TestPage(TemplateView):
    template_name = "test.html"

class ThanksPage(TemplateView):
    template_name = 'thanks.html'

class HomePage(TemplateView):
    template_name = "index.html"

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse("test"))
        return super().get(request, *args, **kwargs)

c221/posts/views.py
from django.shortcuts import render, get_object_or_404,redirect
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.http import Http404
from django.views import generic
from braces.views import SelectRelatedMixin
from posts import forms
from posts import models
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required

# Create your views here.

User = get_user_model()

class PostList(SelectRelatedMixin, generic.ListView):
    model = models.Post
    select_related = ("user",)

class UserPosts(generic.ListView):
    model = models.Post
    template_name = "posts/user_post_list.html"

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related("posts").get(username__iexact=self.kwargs.get("username"))
        
        except User.DoesNotExist:
            raise Http404
            
        else:
            return self.post_user.posts.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["post_user"] = self.post_user
        return context


class PostDetail(SelectRelatedMixin, generic.DetailView):
    model = models.Post
    select_related = ("user",)

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user__username__iexact = self.kwargs.get("username"))

    def get_context_data(self, **kwargs):
        data= super().get_context_data(**kwargs)

        comments_connected = models.Comment.objects.filter(blogpost=self.get_object()).order_by('-created_date')
        data['comments'] = comments_connected
        if self.request.user.is_authenticated:
            data['comment_form']=forms.CommentForm(instance=self.request.user)
        return data

    def post(self,request, *args, **kwargs):
        comment=models.Comment(text=request.POST.get('text'), author=self.request.user, blogpost=self.get_object())
        comment.save()
        return self.get(self,request, *args, **kwargs)

class CreatePost(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
    fields = ('title', 'message')
    model = models.Post

    def form_valid(self,form):
        self.object = form.save(commit = False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class DeletePost(LoginRequiredMixin, SelectRelatedMixin, generic.DeleteView):
    model = models.Post
    select_related = ("user",)
    success_url = reverse_lazy("posts:all")

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id = self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request, "Post Deleted")
        return super().delete(*args, **kwargs)



#@login_required
#def comment_remove(request,pk):
#    comment = get_object_or_404(comment,pk=pk)
#    post_pk=comment.post.pk
#    comment.delete()
#    return redirect('single', pk=post.pk)

c221/accounts/templates/accounts/login.html
{% extends "base.html" %}

{% load bootstrap5 %}

{% block content %}

    <div class= "container">
        <h1>Login</h1>
        <form method="POST" class='form'>
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
            <button type="submit" class=btn btn-primary>Login</button>
            {% endbuttons %}
        </form>
    </div>
{% endblock %}

c221/accounts/templates/accounts/signup.html
{% extends "base.html" %}

{% load bootstrap5 %}

{% block content %}

    <div class= "container">
        <h1>Sign Up!</h1>
        <form method="POST" class='form'>
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
            <button type="submit" class=btn btn-primary>Sign Up</button>
            {% endbuttons %}
        </form>
    </div>
{% endblock %}

c221/posts/templates/posts/_post.html
<div class="media">
    <h3 class="mr-5"><a href="{% url 'posts:for_user' username=post.user.username %}">@{{post.user.username}}</a></h3>
        <h5><a href="{% url 'posts:single' username=post.user.username pk=post.pk %}">{{post.title}} </a></h5>
            <time class="time">{{post.created_at}}</time>
        
        <div class="media-footer">
            {% if user.is_authenticated and post.user == user and not hide_delete %}
                <a href="{% url 'posts:delete' pk=post.pk %}" title="delete" class="btn btn-simple"><span class="fa fa-remove text-danger" aria-hidden="true"></span><span class="text-danger icon-label">Delete</span></a>
            {% endif %}
        </div>
    </div>
</div>

c221/posts/templates/posts/post_base.html
{% extends "base.html" %}

{% block content %}

<div class="post-page">
    <div class="container">
        {% block prepost %} {% endblock %}
        {% block post_content %} {% endblock %}
        {% block post_post %} {% endblock %}
    </div>
</div>

{% endblock %}

c221/posts/templates/posts/post_confirm_delete.html
{% extends "posts/post_base.html" %}

{% block post_content %}
<h3>Are you sure you want to delete this post?</h3>

<div class="posts">
    {% include 'posts/_post.html' %}
</div>

<form method="POST">
    {% csrf_token %}
    <input type="submit" value="Confirm Delete" class="btn btn-danger btn-large">
    <a href="{% url 'posts:single' username=user.username pk=object.pk %}" class="btn btn-light btn-large">Cancel</a>
</form>

{% endblock %}

c221/posts/templates/posts/post_detail.html
{% extends "posts/post_base.html" %}

{% block content %}

    <h1 class="posttitle loader">{{post.title}}</h1>
    
    <p class="postcontent">{{post.message|safe|linebreaksbr}}</p>

    {% if user.is_authenticated %}
    <form method="POST">
        {% csrf_token %}
        <div class="form-group">
            {{comment_form}}
            <button class="btn btn-info" type="submit" >Add comment</button>
        </div>
    </form>
    {% endif %}

    <hr>
    
    <div class="container">
        {% if comments %}
        <strong class="text-secondary">{{ object.number_of_comments }} Comment{{ object.number_of_comments|pluralize }}</strong>
        <hr>
        <ul>
            {% for comment in comments %}
            <li>           
            <div>
                <span>
                <strong class="text-info">{{ comment.author }} </strong>
                <small class="text-muted">{{ comment.created_date }}</small>
                </span>
                <p>
                {{ comment.text|safe }}
                </p>
            </div>
            </li>
            {% endfor %}
        </ul>
        {% else %}
            <strong class="text-secondary">No comments yet...</strong>
        {% endif %}
    </div>

{% endblock %}

c221/posts/templates/posts/post_form.html
{% extends "posts/post_base.html" %}

{% load bootstrap5 %}

{% block post_content %}
<h4>Create New Post</h4>

<form method="POST" action="#" id="postForm">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <button type="submit" class="btn btn-primary btn-large">Post</button>
    {% endbuttons %}

</form>
{% endblock %}

c221/posts/templates/posts/post_list.html
{% extends "posts/post_base.html" %}


{% block post_content %}

<div class="col-md-8">
    {% for post in post_list %}
        {% include "posts/_post.html" %}
        
    {% endfor %}

</div>

{% endblock %}

c221/posts/templates/posts/user_post_list.html
{% extends "posts/post_base.html" %}

{% block prepost %}
<div class="col-md-4">
    <h1>@ {{post_user.username}}</h1>
    <p>Post History</p>
</div>
{% endblock %}

{% block post_content %}
<div class="col-md-8">
    {% for post in post_list %}
        {% include "posts/_post.html" %}
    {% endfor %}

</div>

{% endblock %}

c221/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title></title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light mynav" role="navigation" id="navbar">
            <div class="container-fluid">
                <div class="navbar-nav align-items-center">
                    <a class="navbar-brand" href="{% url 'home' %}">CGC 221</a>
                </div>
                <div class="navbar-nav ml-auto">
                    {% if user.is_authenticated %}
                    <a class="nav-item nav-link" href="{% url 'posts:create' %}" class="btn btn-simple">Post</a>
                    <a class="nav-item nav-link" href="{% url 'accounts:logout' %}" class="btn btn-simple">Log out</a>
                    {% else %}
                    <a class="nav-item nav-link" href="{% url 'accounts:login' %}" class="btn btn-simple">Log in</a>
                    <a class="nav-item nav-link" href="{% url 'accounts:signup' %}" class="btn btn-simple">Sign Up</a>
                    {% endif %}
                </div>
        </nav>
            <div class="container mycontent">
            {% block content %}
    
            {% endblock %}
            </div>
    </body>
</html>

c221/templates/index.html
{% extends "base.html" %}
{% block content %}

    <h1>Welcome to CGC 221</h1>

{% endblock %}

c221/templates/test.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
        <h1>You are now logged in!</h1>
        <h2><a href="{% url 'posts:all' %}">Go to Posts</a></h2>
    </div>
        

{% endblock %}

c221/templates/thanks.html
{% extends "base.html" %}
{% block content %}
    <h1>Thanks for visiting! come back soon!</h1>
{% endblock %}